// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR28yHaxLsxqK6QbsM_km5WRE2plVIsM0',
    appId: '1:1041311320518:web:76f8692ebc2d2217afcac7',
    messagingSenderId: '1041311320518',
    projectId: 'thigk-95d57',
    authDomain: 'thigk-95d57.firebaseapp.com',
    storageBucket: 'thigk-95d57.appspot.com',
    measurementId: 'G-HPP1TBS7TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3cP6ksZXmlu_eEXqcsQ_CD_vLR9oDD2E',
    appId: '1:1041311320518:android:d24e7a4ae6b96dc8afcac7',
    messagingSenderId: '1041311320518',
    projectId: 'thigk-95d57',
    storageBucket: 'thigk-95d57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEDqfK6tb6svqt5dMCMSl7PeBvpuf9mcQ',
    appId: '1:1041311320518:ios:7a78d519eabcbb9dafcac7',
    messagingSenderId: '1041311320518',
    projectId: 'thigk-95d57',
    storageBucket: 'thigk-95d57.appspot.com',
    iosBundleId: 'com.example.thigk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEDqfK6tb6svqt5dMCMSl7PeBvpuf9mcQ',
    appId: '1:1041311320518:ios:7a78d519eabcbb9dafcac7',
    messagingSenderId: '1041311320518',
    projectId: 'thigk-95d57',
    storageBucket: 'thigk-95d57.appspot.com',
    iosBundleId: 'com.example.thigk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR28yHaxLsxqK6QbsM_km5WRE2plVIsM0',
    appId: '1:1041311320518:web:07c417284ef8b2b5afcac7',
    messagingSenderId: '1041311320518',
    projectId: 'thigk-95d57',
    authDomain: 'thigk-95d57.firebaseapp.com',
    storageBucket: 'thigk-95d57.appspot.com',
    measurementId: 'G-4L3LPH2XYK',
  );
}
